server:
  port: 8092

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orchestra
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true